name: tabg-server
services:
    tabg-server:
        restart: unless-stopped
        container_name: server1
        volumes:
            - ./data/game_settings.txt:/tabg-server/game_settings.txt:rw
            - ./data/ExtraSettings.json:/tabg-server/ExtraSettings.json:rw
            - ./data/Guestbook.txt:/tabg-server/Guestbook.txt:rw
            - ./data/PlayerPerms.json:/tabg-server/PlayerPerms.json:rw
            - ./data/Commands_List.txt:/tabg-server/Commands_List.txt:rw
            - ./data/plugins:/tabg-server/BepInEx/plugins/usr:rw
            - ./data/LootTables:/tabg-server/LootTables:rw
        image: tabg-server